version: '3.3'
services:
  # app:
  #   build: .
  #   container_name: app
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - mysql
  #   environment:
  #     - WAIT_HOSTS=mysql:3306
  mysql:
    image: mysql:8.0.32
    container_name: mysql
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      - MYSQL_ROOT_PASSWORD=123456

volumes:
  mysql: