### admin create
GET http://127.0.0.1:8000/api/admin HTTP/1.1
Content-Type: application/x-www-form-urlencoded

### admin login
POST http://127.0.0.1:8000/api/admin/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=admin&password=admin


### user create

POST http://127.0.0.1:8000/api/v1/admin/user/create?expire_at=1650459189000&remaining=10 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInNjb3BlcyI6W10sImV4cCI6MTY4MjA3NjIyNH0.JJ3hxqnsQUmIE-AFwz3rGoQ1ZWC2kFRxSgSlR3kNjeU

grant_type=password&username=onekki&password=onekki&scope=users


### user profile

GET http://127.0.0.1:8000/api/v1/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJvbmVra2kiLCJzY29wZXMiOltdLCJleHAiOjE2NTA0NTkxODkwMDB9.zOsb9yXyRw6avZ2RO1pd43zalTHJLjbkvsoihd9uDnk


### user profile
GET http://127.0.0.1:8000/api/v1/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJvbmVra2kzIiwic2NvcGVzIjpbInVzZXJzIl0sImV4cCI6MTY1MDQ1OTE4OTAwMH0.KszDaKdNlzTPPKPniH2c1gs3tKr5YXnyItdMzHUFiug
