name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to custom Docker registry
        run: echo ${{ secrets.DOCKER_REGISTRY_PASSWORD }} | docker login -u ${{ vars.DOCKER_REGISTRY_USERNAME }} --password-stdin registry.baidubce.com

      # - name: Build pipenv and push Docker image
      #   run: |
      #     docker build -t registry.baidubce.com/miss-journey/pipenv:${{ github.sha }} ./dockerfiles/pipenv
      #     docker push registry.baidubce.com/miss-journey/pipenv:${{ github.sha }}
      - name: Build and push Docker image
        run: |
          docker pull registry.baidubce.com/miss-journey/pipenv:latest
          docker build -t registry.baidubce.com/miss-journey/bot:${{ github.sha }} ./dockerfiles/bot
          docker push registry.baidubce.com/miss-journey/journey:${{ github.sha }}