name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to custom Docker registry
        run: echo ${{ secrets.DOCKER_REGISTRY_PASSWORD }} | docker login -u ${{ vars.DOCKER_REGISTRY_USERNAME }} --password-stdin registry.baidubce.com

      - name: Build pipenv and push Docker image
        run: |
          docker build -t registry.baidubce.com/miss-journey/pipenv:latest ./dockerfiles/pipenv
          docker push registry.baidubce.com/miss-journey/pipenv:latest
      - name: Build and push Docker image
        run: |
          docker build -t registry.baidubce.com/miss-journey/journey:${{ github.sha }} -f ./dockerfiles/journey/Dockerfile  .
          docker tag registry.baidubce.com/miss-journey/journey:${{ github.sha }} registry.baidubce.com/miss-journey/journey:latest
          docker push registry.baidubce.com/miss-journey/journey:${{ github.sha }}
          docker push registry.baidubce.com/miss-journey/journey:latest
      - name: SSH into server and pull Docker image
        uses: appleboy/ssh-action@master
        with:
          host: 198.12.121.219
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ~/bot
            echo ${{ secrets.DOCKER_REGISTRY_PASSWORD }} | docker login -u ${{ vars.DOCKER_REGISTRY_USERNAME }} --password-stdin registry.baidubce.com
            docker pull registry.baidubce.com/miss-journey/journey:latest     
            docker run registry.baidubce.com/miss-journey/journey:latest  --env-file .env  python ./bot-v2.py